# -*- coding: utf-8 -*-
"""Cnctenar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OJVhxz4taqkTHHWYQI5o8a4Ff00ShUd3
"""

#concatenar cadenas de caracteres
# vamos a crear una cadena que diga: “La principal ventaja de los DATOS es que te dicen algo sobre el mundo que no sabías antes"

# Vcompletar = "datos"

# print("La principal ventaja de los " + Vcompletar + " es que te dicen algo sobre el mundo que no sabías antes")
# print("La principal ventaja de los {} es que te dicen algo sobre el mundo que no sabías antes".format(Vcompletar))
# print(f"La principal ventaja de los {Vcompletar} es que te dicen algo sobre el mundo que no sabías antes")


#Completar parrafos
#"La ciencia de {datos} es un campo multidisciplinario que se encarga de estudiar los datos para extraer conocimientos y tomar {decisiones} informadas: Combina disciplinas como la estadística, las {matemáticas}, la ingeniería de computación y la inteligencia artificial. Se encarga de obtener, procesar y analizar datos para generar {información}.)
print("La ciencia de {Palabra1} es un campo multidisciplinario que se encarga de estudiar los datos para extraer conocimientos y tomar {Palabra2} informadas: Combina disciplinas como la estadística, las {Palabra3}, la ingeniería de computación y la inteligencia artificial. Se encarga de obtener, procesar y analizar datos para generar {Palabra4}.")
Palabra1 = input( "Palabra 1: ")
Palabra2 = input( "Palabra 2: ")
Palabra3 = input( "Palabra 3: ")
Palabra4 = input( "Palabra 4: ")

parrafo = f"La ciencia de {Palabra1} es un campo multidisciplinario que se encarga de estudiar los datos para extraer conocimientos y tomar {Palabra2} informadas: Combina disciplinas como la estadística, las {Palabra3}, la ingeniería de computación y la inteligencia artificial. Se encarga de obtener, procesar y analizar datos para generar {Palabra4}."

print(parrafo)